###
POST http://localhost:3000/register
content-type: application/json

{
    "userName": "mayofdfgd", 
    "password": "m123456",
    "firstName": "may",
    "lastName": "v",
    "accountType": "Referee",
    "refType": "main_referee"
}

###
POST http://localhost:3000/login
content-type: application/json


{
    "userName": "may",
    "password": "m123456"
}

###
POST http://localhost:3000/addRefereeToSeason
content-type: application/json

{
    "refereeUserName": "may",
    "league": "league1",
    "season": "league1_2021"
}

###
POST http://localhost:3000/scheduleMatchesSeasonInLeague
content-type: application/json
{
    "league": "league1",
    "season": "league1_2021"
}
